# docker-compose.yml
version: '3.12'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      args:
        ARG: <ARG>
    image: ift6758/serving:latest
    ports:
      - 5000:5000
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
    volumes:
      - ./serving/models:/code/models
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
##      args:
##        ARG: <ARG>
    image: ift6758/streamlit:latest
    ports:
      - 8501:8501
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
##      OTHER_DOCKER_ENV_VAR = ${OTHER_LOCAL_ENV_VAR}
      

     
